# -*- coding: utf-8 -*-
"""first_neural_network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DXm0LzA9_SC0cuqHvIOYIBfswCY6B-5J
"""

import numpy as np

def sigmoid(x):
  
  return 1 / (1 + np.exp(-x))

i1 = .05
i2 = .10

w1 = .15
w2 = .20
w3 = .25
w4 = .30
w5 = .40
w6 = .45
w7 = .50
w8 = .55

b1 = .35
b2 = .60

weight = np.array([[w1,w3], [w2,w4]])
inputs = np.array([i1,i2])


h1h2 = sigmoid(np.dot(inputs,weight)+ b1 )
print(h1h2)


weight2 = np.array([[w5,w7], [w6,w8]])
o1o2 = sigmoid(np.dot(h1h2,weight2)+b2)
print(o1o2)